version: '3.8'

services:
  # MongoDB container
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

  # Node.js app container
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mydatabase
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb_data:
